--CREATE
CREATE TABLE SAMPLE2(REGION BIGINT,SALES BIGINT) 
DROP TABLE REGION
CREATE TABLE REGION (REGION BIGINT,RNAME CHAR(50))
--INSERT
INSERT INTO SAMPLE2 VALUES(1,100)
INSERT INTO SAMPLE2 VALUES(2,150)
INSERT INTO SAMPLE2 VALUES(3,250)
INSERT INTO SAMPLE2 VALUES(4,250)
--READ
SELECT * FROM SAMPLE2
SELECT * FROM REGION
SELECT COUNT(*)FROM SAMPLE2
--UPDATE
UPDATE SAMPLE2 SET SALES=150 WHERE REGION=1
--DELETE
DELETE FROM SAMPLE2 WHERE REGION=1
DELETE FROM REGION
--INSERT INTO REGION TABLE
INSERT INTO REGION VALUES(1,'NDL')
INSERT INTO REGION VALUES(2,'BLR')
INSERT INTO REGION VALUES(3,'HYD')
INSERT INTO REGION VALUES(4,'MUM')

--REPORTING WITH JOIN
SELECT T2.RNAME AS REGION,T1.SALES AS SALES
FROM SAMPLE2 T1,REGION T2
WHERE T1.REGION=T2.REGION
--SORTED REPORT
SELECT T2.RNAME AS REGION,T1.SALES AS SALES
FROM SAMPLE2 T1,REGION T2
WHERE T1.REGION=T2.REGION
ORDER BY T1.SALES DESC


